---
- name: Stop and remove any existing container
  docker_container:
    name: plexrequests
    state: absent

- name: Create and start container
  docker_container:
    name: plexrequests
    image: "linuxserver/plexrequests"
    published_ports:
      - "127.0.0.1:3000:3000"
    env:
      PUID: "{{uid.stdout}}"
      PGID: "{{gid.stdout}}"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/plexrequests:/config"
    networks:
      - name: cloudbox
        ipv4_address: 172.18.0.17
        aliases:
          - plexrequests
    labels:
      traefik.port: "3000"
    restart_policy: always
    state: started
