---
  user: seed
  passwd: password123
  domain: testcloudbox.ml
  email: your@email.com
  mnt: 
    local: "/mnt/local"
    unionfs: "/mnt/unionfs"
    docker_data: "/opt"
    fuse_dir: "/mnt/local/.unionfs-fuse"
    plexdrive: "/mnt/plexdrive"
  nzbget:
    downloads: "{{mnt.unionfs}}/downloads/nzbget"
  rutorrent:
    passwd: password321
    downloads: "/home/{{user}}/downloads/rutorrent"
  plex:
    tag: public
    transcodes: "/dev/shm"
    enable_dri: "True"
  plex_autoscan:
    ip: "0.0.0.0"
  rclone:
    version: 1.36
    bwlimit: 
    checkers: 8
    transfers: 16
    local_dir: "{{mnt.local}}/Media"
    remote_dir: "agdrive:/Media"
    rm_empty_dirs:
      - "{{mnt.local}}/Movies"
      - "{{mnt.local}}/Kids Movies"
      - "{{mnt.local}}/TV"
      - "{{mnt.local}}/Kids TV"
    excludes:
      - "**partial~"
      - "**_HIDDEN"
      - ".unionfs/**"
      - ".unionfs-fuse/**"
  unionfs_cleaner:
    max_local_gigabytes: 400
    size_check_mins: 5
    config_manager: true
    git_autoupdater: true
    upload_manager: true
  backup:
    tgz_dest: "/home/{{user}}/Backups"
    rsync_dest: rsync://somehost.com/Backups
    rclone_dest: agdrive:/Backups
    use_rsync: false
    use_rclone: false
    stop_plex: false
    cron_time: weekly
    cron_state: absent
  http_auth:
    enable: True
    sites:
      - hydra
      - jackett
      - organizr
      - plexpy
      - plexrequests
      - portainer
      - radarr
      - sonarr
      - nzbget
  docker_volumes:
    radarr:
      - "{{mnt.unionfs}}:{{mnt.unionfs}}"
      - "{{mnt.local}}:{{mnt.local}}"
    nzbget:
      - "{{mnt.unionfs}}:{{mnt.unionfs}}"
      - "{{mnt.local}}:{{mnt.local}}"
    sonarr:
      - "{{mnt.unionfs}}:{{mnt.unionfs}}"
      - "{{mnt.local}}:{{mnt.local}}"
    plex:
      - "{{mnt.unionfs}}/Media:/data/.media"
  watchtower_monitor:
    - organizr
    - plexpy
    - plexrequests
    - radarr
    - sonarr
    - nzbget
  pushover:
    - app_token: 
    - user_token:
