---
  user: seed
  passwd: password123
  domain: cloudbox.gq
  email: your@email.com
  nzbget:
    downloads: "/home/{{user}}/downloads/nzbget"
  rutorrent:
    downloads: "/home/{{user}}/downloads/rutorrent"
    user: seed
    passwd: sekret321
  plex:
    tag: public
    transcodes: "/home/{{user}}/transcodes"
  plexdrive:
    client_id: ""
    client_secret: ""
  plex_autoscan:
    ip: "0.0.0.0"
  rclone:
    version: 1.36
  unionfs_cleaner:
    max_local_gigabytes: 200
    size_check_mins: 30
    rclone_remote: "google:"
  backup:
    tgz_dest: "/home/{{user}}/Backups"
    rsync_dest: rsync://somehost.com/Backups
    rclone_dest: google:/Backups
    use_rsync: false
    use_rclone: false
    stop_plex: false
    cron_time: weekly
    cron_state: absent