---
  user: seed
  passwd: password123
  domain: testcloudbox.ml
  email: your@email.com
  mnt: 
    local: "/mnt/local/Media"
    unionfs: "/mnt/unionfs/Media"
    docker_data: "/opt"
    fuse_dir: "/mnt/local/.unionfs-fuse"
    plexdrive: "/mnt/plexdrive"
  nzbget:
    downloads: "/home/{{user}}/downloads/nzbget"
  rutorrent:
    passwd: password321
    downloads: "/home/{{user}}/downloads/rutorrent"
  plex:
    tag: public
    transcodes: "/dev/shm"
    enable_dri: "True"
  plex_autoscan:
    ip: "0.0.0.0"
  rclone:
    version: 1.36
#    bwlimit: 
    checkers: 8
    transfers: 16
    rm_empty_dirs:
      - Movies
      - Kids Movies
      - TV
      - Kids TV
    excludes:
      - ""**partial~""
      - ""**_HIDDEN"
      - ".unionfs/**""
      - ".unionfs-fuse/**"  
  unionfs_cleaner:
    max_local_gigabytes: 500
    size_check_mins: 5
    rclone_remote: "agdrive:/Media"
  backup:
    tgz_dest: "/home/{{user}}/Backups"
    rsync_dest: rsync://somehost.com/Backups
    rclone_dest: agdrive:/Backups
    use_rsync: false
    use_rclone: false
    stop_plex: false
    cron_time: weekly
    cron_state: absent
  http_auth:
    enable: True
    sites:
      - hydra
      - jackett
      - organizr
      - plexpy
      - plexrequests
      - portainer
      - radarr
      - sonarr
      - nzbget
  docker_volumes:
    radarr:
      - "{{mnt.unionfs}}/Movies:/movies"
      - "{{mnt.unionfs}}/Kids Movies:/kids movies"
      - "{{nzbget.downloads}}:/downloads/nzbget"
      - "{{rutorrent.downloads}}:/downloads/rutorrent"
    sonarr:
      - "{{mnt.unionfs}}/TV:/tv"
      - "{{mnt.unionfs}}/Kids TV:/kids tv"
      - "{{nzbget.downloads}}:/downloads/nzbget"
      - "{{rutorrent.downloads}}:/downloads/rutorrent"
    plex:
      - "{{mnt.unionfs}}:/data/.media"
  watchtower_list:
    - organizr
    - plexpy
    - plexrequests
    - radarr
    - sonarr
    - nzbget
  unionfs_cleaner:
    config_manager: true
    git_autoupdater: true
    upload_manager: true
  pushover:
    - app_token: 
    - user_token:

