---
- name: Stop and remove any existing container
  docker_container:
    name: watchtower
    state: absent

- name: Create and start container
  docker_container:
    name: watchtower
    image: "v2tec/watchtower"
    command: '{{watchtower.command + watchtower.monitor}}'
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart_policy: always
    networks:
      - name: cloudbox
        ipv4_address: 172.18.0.5
        aliases:
          - watchtower
    state: started
