---
- name: Stop and remove any existing container
  docker_container:
    name: netdata
    state: absent

- name: Create and start container
  docker_container:
    name: netdata
    image: "titpetric/netdata:latest"
    capabilities:
      - SYS_PTRACE
    published_ports:
      - "127.0.0.1:19999:19999"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/proc:/host/proc:ro"
      - "/sys:/host/sys:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - name: cloudbox
        aliases:
          - netdata
    labels:
      traefik.port: "19999"
      traefik.frontend.auth.basic: "seed:$apr1$rIGITnks$AESJ1N8/KFspvhK49oj2h1"
    restart_policy: always
    state: started
