---
- name: Stop and remove any existing container
  docker_container:
    name: netdata
    state: absent

- name: Create and start container
  docker_container:
    name: netdata
    image: "titpetric/netdata:latest"
    command: "--cap-add=SYS_PTRACE"
    published_ports:
      - "19999:19999"
    env:
      NETDATA_IP: "127.0.0.1"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/proc:/host/proc:ro"
      - "/sys:/host/sys:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - name: cloudbox
        aliases:
          - netdata
    labels:
      traefik.port: "19999"
    restart_policy: always
    state: started
