---
  - name: Install mongodb
      apt: 
        name: mongodb
        state: installed

  - name: Install plexdrive
    get_url:
      url:  https://github.com/dweidenfeld/plexdrive/releases/download/4.1.0-beta-1498397749/plexdrive-linux-amd64
      dest: /opt/plexdrive/plexdrive
      mode: 0755
      owner: "{{user}}"
      group: "{{user}}"

  - name: Import plexdrive.service
      src: plexdrive.service.js2
      dest: /etc/systemd/system/plexdrive.service 
      force: yes

  - name: Start plexdrive service
    systemd: state=stopped name=plexdrive daemon_reload=yes enabled=no