---
  - name: Install mongodb
    apt: 
      name: mongodb
      state: installed

  - name: Install plexdrive
    get_url:
      url:  https://github.com/dweidenfeld/plexdrive/releases/download/4.1.0-beta-1498397749/plexdrive-linux-amd64
      dest: /opt/plexdrive/plexdrive
      mode: 0755
      owner: "{{user}}"
      group: "{{user}}"

  - name: Import plexdrive.service
    template:
      src: plexdrive.service.js2
      dest: /etc/systemd/system/plexdrive.service 
      force: yes

  - name: Systemd daemon-reload
    systemd: state=stopped name=plexdrive daemon_reload=yes enabled=no

  - name: Check config exists
    stat:
      path: "/opt/plexdrive/config.json"
      register: config_file

  - name: Start plexdrive service
    systemd: state=started name=plexdrive enabled=yes
    when: config_file.stat.exists
    ignore_errors: True