---
- name: "Unarchive rclone v{{rclone.version}}"
  unarchive:
    src: https://github.com/ncw/rclone/releases/download/v{{ rclone.version }}/rclone-v{{ rclone.version }}-linux-amd64.zip
    dest: /tmp
    copy: no

- name: Copy binary to /opt/rclone
  copy:
    src: "/tmp/rclone-v{{ rclone.version }}-linux-amd64/rclone"
    dest: /opt/rclone/rclone
    mode: 0777
    owner: {{user}}
    group: {{user}}

- name: Symlink binary to /usr/sbin
  file:
    src: /opt/rclone/rclone
    dest: /usr/sbin/rclone
    state: link
    force: yes

- name: Make dir for local manpages
  file:
    path: '/usr/local/share/man/man1'
    state: directory
    mode: 0775
    owner: root
    group: root

- name: Copy manpage
  copy:
    src: "/tmp/rclone-v{{ rclone.version }}-linux-amd64/rclone.1"
    dest: /usr/local/share/man/man1/rclone.1
    mode: 0644
    owner: root
    group: root

- name: Install manpage
  shell: mandb
  changed_when: false

- name: Symlink config
  file:
    src: "/home/{{user}}/.config/rclone/rclone.conf"
    dest: /opt/rclone/rclone.conf
    state: link
    force: yes