---
- name: Stop and remove any existing container
  docker_container:
    name: rutorrent
    image: linuxserver/rutorrent
    state: absent

- name: Create and start container
  docker_container:
    name: rutorrent
    image: linuxserver/rutorrent
    ports:
      - "{{rutorrent.port}}:{{rutorrent.port}}"
      - "51413:51413"
      - "6881:6881/udp"
    env:
      PUID: "{{uid.stdout}}"
      PGID: "{{gid.stdout}}"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/rutorrent:/config"
      - "{{rutorrent.downloads}}:/downloads/rutorrent"
    restart_policy: always
    net: host
    state: started
