- name: Stop and remove any existing container
  docker_container:
    name: cadvisor
    state: absent

- name: Create htpasswd
  htpasswd:
    path: /opt/cadvisor/htpasswd
    name: "{{user}}"
    password: "{{cadvisor.passwd}}"
    owner: "{{user}}"
    group: "{{user}}"
    mode: 0775

- name: Create and start container
  docker_container:
    name: cadvisor
    image: "google/cadvisor:latest"
    published_ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
      - "/opt/cadvisor:/config:ro"
    env:
      VIRTUAL_HOST: "cadvisor.{{domain}}"
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: "cadvisor.{{domain}}"
      LETSENCRYPT_EMAIL: "{{email}}"
    command: "--http_auth_file=/config/htpasswd"
    networks:
      - name: cloudbox
        ipv4_address: 172.18.0.20
        aliases:
          - cadvisor
    restart_policy: always
    state: started
