---
- name: "Archiving /opt to /home/{{user}}/backups/cloudbox_{{date}}.tgz"
  vars:
    backup_date: "{{ lookup('pipe', 'date +%Y%m%d_%H%M') }}"
  archive:
    path: /opt
    dest: "{{backup.dest}}/cloudbox_{{backup_date}}.tgz"
    owner: "{{user}}"
    group: "{{user}}"