---
- block:
  - name: "Check {{backup.tgz_dest}} exists"
    stat:
      path: "{{backup.tgz_dest}}"
    register: backup_location

  - name: "Create backup location {{backup.tgz_dest}}"
    file: path={{backup.tgz_dest}} state=directory mode=0775 owner={{user}} group={{user}} recurse=true
    when: backup_location.stat.exists == False

  - name: "Check if backup.lock is present"
    stat:
      path: "{{playbook_dir}}/backup.lock"
    register: backup_lock

  - name: "Fail when backup.lock exists"
    fail:
      msg: "Backup is already in progress..."
    when: backup_lock.stat.exists

  - name: "Create backup.lock"
    file:
      path: "{{playbook_dir}}/backup.lock"
      state: touch
      owner: "{{user}}"
      group: "{{user}}"
    when: backup_lock.stat.exists == False

  - name: "Check {{backup.tgz_dest}}/cloudbox.tgz exists"
    stat:
      path: "{{backup.tgz_dest}}/cloudbox.tgz"
    register: backup_previous_tgz

  - name: "Copying cloudbox.tgz to cloudbox.tgz.backup"
    copy:
      src: "{{backup.tgz_dest}}/cloudbox.tgz"
      dest: "{{backup.tgz_dest}}/cloudbox.tgz.backup"
      force: yes
      group: "{{user}}"
      owner: "{{user}}"
    when: backup_previous_tgz.stat.exists

  - name: "Remove previous cloudbox.tgz"
    file:
      path: "{{backup.tgz_dest}}/cloudbox.tgz"
      state: absent
    when: backup_previous_tgz.stat.exists

  - name: "Copy settings.xml to /opt for inclusion in backup"
    copy:
      src: "{{playbook_dir}}/settings.yml"
      dest: "/opt/settings.yml"
      force: yes
      group: "{{user}}"
      owner: "{{user}}"
      mode: 0775

  - name: "Stop Plex"
    docker_container:
      name: plex
      image: "plexinc/pms-docker:{{plex.tag}}"
      state: stopped
    when: backup.stop_plex

  - name: "Archiving /opt to {{backup.tgz_dest}}/cloudbox.tgz"
    archive:
      path: "/opt/*"
      dest: "{{backup.tgz_dest}}/cloudbox.tgz"
      owner: "{{user}}"
      group: "{{user}}"

  - name: "Start Plex"
    docker_container:
      name: plex
      image: "plexinc/pms-docker:{{plex.tag}}"
      state: started
    when: backup.stop_plex
  
  - name: "Upload backups with rclone to {{backup.rclone_dest}}"
    command: "rclone copy '{{backup.tgz_dest}}' '{{backup.rclone_dest}}' --stats=30s -v --transfers=2 --log-file='{{playbook_dir}}/backup_rclone.log'"
    become: true
    become_user: "{{user}}"
    when: backup.use_rclone

  - name: "Upload backups with rsync to {{backup.rsync_dest}}"
    synchronize:
      src: "{{backup.tgz_dest}}/"
      dest: "{{backup.rsync_dest}}/"
      rsync_opts:
        - "--log-file='{{playbook_dir}}/backup_rsync.log'"
    become: true
    become_user: "{{user}}"
    when: backup.use_rsync

  - name: "Schedule cron backup for state: {{backup.cron_state}}, when: {{backup.cron_time}}"
    cron:
      name: "Backup Cloudbox"
      special_time: "{{backup.cron_time}}"
      job: "ansible-playbook {{playbook_dir}}/cloudbox.yml --tags backup"
      state: "{{backup.cron_state}}"

  always:
  - debug: msg="Finished backup"
    when: backup_lock.stat.exists == False

  - name: "Remove backup.lock"
    file:
      path: "{{playbook_dir}}/backup.lock"
      state: absent
    when: backup_lock.stat.exists == False