---
- name: Stop and remove any existing container
  docker_container:
    name: radarr
    image: hotio/radarr
    state: absent

- name: Create and start container
  docker_container:
    name: radarr
    image: hotio/radarr
    ports:
      - "{{radarr.port}}:{{radarr.port}}"
    env:
      PUID: "{{uid.stdout}}"
      PGID: "{{gid.stdout}}"
      VERSION: latest
      MONO_TLS_PROVIDER: legacy
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/radarr:/config"
      - "/mnt/unionfs/Media/Movies:/movies"
      - "{{nzbget.downloads}}:/downloads/nzbget"
      - "{{rutorrent.downloads}}:/downloads/rutorrent"
    restart_policy: always
    network_mode: host
    state: started
