---
- name: Update packages
  apt:
    update_cache: yes

- name: Install apt-utils
  apt: "name=apt-utils state=latest"

- name: Upgrade packages
  apt:
    upgrade: dist

- name: Upgrade kernel
  apt:
    name: linux-generic-hwe-16.04
    state: latest

- name: Enable tcp_window_scaling in sysctl.conf
  ini_file:
    path: /etc/sysctl.conf
    section: null
    option: "net.ipv4.tcp_window_scaling"
    value: 1
    state: present

- name: Increase rmem_max test buffer limit to 64 MB in sysctl.conf
  ini_file:
    path: /etc/sysctl.conf
    section: null
    option: "net.core.rmem_max"
    value: 67108864
    state: present

- name: Increase wmem_max test buffer limit to 64 MB in sysctl.conf
  ini_file:
    path: /etc/sysctl.conf
    section: null
    option: "net.core.wmem_max"
    value: 67108864
    state: present

- name: Increase tcp_rmem autotune buffer limit to 32 MB in sysctl.conf
  ini_file:
    path: /etc/sysctl.conf
    section: null
    option: "net.ipv4.tcp_rmem"
    value: "4096 87380 33554432"
    state: present
    
- name: Increase tcp_wmem autotune buffer limit to 32 MB in sysctl.conf
  ini_file:
    path: /etc/sysctl.conf
    section: null
    option: "net.ipv4.tcp_wmem"
    value: "4096 87380 33554432"
    state: present

- name: Set tcp_congestion_control to bbr in sysctl.conf
  ini_file:
    path: /etc/sysctl.conf
    section: null
    option: "net.ipv4.tcp_congestion_control"
    value: bbr
    state: present

- debug:
    msg: "System {{ inventory_hostname }} has interface {{ ansible_default_ipv4.interface }}"
  when: ansible_default_ipv4.interface is defined
