---
- name: Update packages
  apt:
    update_cache: yes

- name: Install required packages
  apt: "name={{item}} state=latest"
  with_items:
    - apt-utils
    - byobu

- name: Upgrade kernel
  apt:
    name: linux-generic-hwe-16.04
    state: latest

- name: Purge old kernels on reboot
  cron:
    name: "Remove old kernels on reboot"
    special_time: reboot
    job: "purge-old-kernels"

- name: Upgrade packages
  apt:
    upgrade: dist

- name: Enable tcp_window_scaling
  sysctl:
    name: net.ipv4.tcp_window_scaling
    value: 1
    state: present

- name: Increase rmem_max test buffer limit to 64 MB
  sysctl:
    name: net.core.rmem_max
    value: 67108864
    state: present

- name: Increase wmem_max test buffer limit to 64 MB
  sysctl:
    name: net.core.wmem_max
    value: 67108864
    state: present

- name: Increase tcp_rmem autotune buffer limit to 32 MB
  sysctl:
    name: net.ipv4.tcp_rmem
    value: "4096 87380 33554432"
    state: present
    
- name: Increase tcp_wmem autotune buffer limit to 32 MB
  sysctl:
    name: net.ipv4.tcp_wmem
    value: "4096 87380 33554432"
    state: present

- name: Set tcp_congestion_control to bbr
  sysctl:
    name: net.ipv4.tcp_congestion_control
    value: bbr
    state: present
    reload: no

- name: Increase system file descriptor limit
  sysctl:
    name: fs.file-max
    value: 100000
    state: present

- name: Reduce swappiness
  sysctl:
    name: vm.swappiness
    value: 10
    state: present

- name: Increase netdev_max_backlog
  sysctl:
    name: net.core.netdev_max_backlog
    value: 50000
    state: present

- name: Increase tcp_max_syn_backlog
  sysctl:
    name: net.ipv4.tcp_max_syn_backlog
    value: 30000
    state: present

- name: Increase tcp_max_tw_buckets
  sysctl:
    name: net.ipv4.tcp_max_tw_buckets
    value: 2000000
    state: present

- name: Enable tcp_tw_reuse
  sysctl:
    name: net.ipv4.tcp_tw_reuse
    value: 1
    state: present

- name: Increase tcp_fin_timeout
  sysctl:
    name: net.ipv4.tcp_fin_timeout
    value: 10
    state: present

- name: Disable tcp_slow_start_after_idle
  sysctl:
    name: net.ipv4.tcp_slow_start_after_idle
    value: 0
    state: present

- name: Increase udp_rmem_min
  sysctl:
    name: net.ipv4.udp_rmem_min
    value: 8192
    state: present

- name: Increase udp_wmem_min
  sysctl:
    name: net.ipv4.udp_wmem_min
    value: 8192
    state: present

- name: Disable accept_source_route
  sysctl:
    name: net.ipv4.conf.all.accept_source_route
    value: 0
    state: present

- name: Disable accept_redirects
  sysctl:
    name: net.ipv4.conf.all.accept_redirects
    value: 0
    state: present

- name: Disable secure_redirects 
  sysctl:
    name: net.ipv4.conf.all.secure_redirects 
    value: 0
    state: present

- name: Set default_qdisc to fq
  sysctl:
    name: net.core.default_qdisc
    value: fq
    state: present

- debug:
    msg: "System {{ inventory_hostname }} has interface {{ ansible_default_ipv4.interface }}"
  when: ansible_default_ipv4.interface is defined

- name: "Set RX/TX ring params on boot for default network interface"
  cron:
    name: "Set RX/TX ring params on boot"
    special_time: reboot
    job: "ethtool -G {{ ansible_default_ipv4.interface }} rx 8192 && ethtool -G {{ ansible_default_ipv4.interface }} tx 8192"
  when: ansible_default_ipv4.interface is defined

