---
- name: Update packages
  apt:
    update_cache: yes

- name: Install apt-utils
  apt: "name=apt-utils state=latest"

- name: Upgrade packages
  apt:
    upgrade: dist

- name: Upgrade kernel
  apt:
    name: linux-generic-hwe-16.04
    state: latest