---
- name: Stop and remove any existing container
  docker_container:
    name: nzbget
    image: linuxserver/nzbget
    state: absent

- name: Create and start container
  docker_container:
    name: nzbget
    image: linuxserver/nzbget
    ports:
      - "{{nzbget.port}}:{{nzbget.port}}"
    env:
      PUID: "{{uid.stdout}}"
      PGID: "{{gid.stdout}}"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/nzbget:/config"
      - "{{nzbget.downloads}}:/downloads/nzbget"
    restart_policy: always
    network_mode: host
    state: started

