---
- name: Stop and remove any existing container
  docker_container:
    name: sonarr
    state: absent
- name: Setup two lists to be merged
  set_fact:
    sonarr_volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "{{mnt.docker_data}}/sonarr:/config"
      - "{{nzbget.downloads}}:/downloads/nzbget"
      - "{{rutorrent.downloads}}:/downloads/rutorrent"
      - "{{mnt.docker_data}}/scripts:/scripts"

- name: Create and start container
  docker_container:
    name: sonarr
    image: "hotio/suitarr"
    published_ports:
      - "127.0.0.1:8989:8080"
    env:      
      APP: "sonarr"
      VERSION: "unstable"
      BACKUP: "yes"
      PUID: "{{uid.stdout}}"
      PGID: "{{gid.stdout}}"
      MONO_TLS_PROVIDER: legacy
      VIRTUAL_HOST: "sonarr.{{domain}}"
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: "sonarr.{{domain}}"
      LETSENCRYPT_EMAIL: "{{email}}"
    volumes: "{{docker_volumes.sonarr}} + {{sonarr_volumes}}"    
    networks:
      - name: cloudbox
        ipv4_address: 172.18.0.13
        aliases:
          - sonarr
    restart_policy: always
    state: started
