---
- name: Stop and remove any existing container
  docker:
    name: plexpy
    image: linuxserver/plexpy
    state: absent

- name: Create and start container
  docker:
    name: plexpy
    image: linuxserver/plexpy
    ports:
      - "{{plexpy.port}}:{{plexpy.port}}"
    env:
      PUID: "{{uid.stdout}}"
      PGID: "{{gid.stdout}}"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/plexpy:/config"
      - "/opt/plex/Library/Application Support/Plex Media Server/Logs:/logs:ro"
    restart_policy: always
    net: host
    state: started

