---
- name: Stop and remove any existing container
  docker_container:
    name: nzbhydra
    state: absent

- name: Create and start container
  docker_container:
    name: nzbhydra
    image: linuxserver/hydra
    published_ports:
      - "127.0.0.1:5075:5075"
    env:
      PUID: "{{uid.stdout}}"
      PGID: "{{gid.stdout}}"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/nzbhydra:/config"
    restart_policy: always
    networks:
      - name: cloudbox
        ipv4_address: 172.18.0.12
        aliases:
          - nzbhydra
    labels:
      traefik.port: "5075"
    state: started
