---
- name: Stop and remove any existing container
  docker_container:
    name: nzbhydra
    image: linuxserver/hydra
    state: absent

- name: Create and start container
  docker_container:
    name: nzbhydra
    image: linuxserver/hydra
    published_ports:
      - "{{nzbhydra.port}}:{{nzbhydra.port}}"
    env:
      PUID: "{{uid.stdout}}"
      PGID: "{{gid.stdout}}"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/nzbhydra:/config"
    restart_policy: always
    network_mode: host
    state: started
