---
- name: Stop and remove any existing container
  docker_container:
    name: jackett
    image: linuxserver/jackett
    state: absent

- name: Create and start container
  docker_container:
    name: jackett
    image: linuxserver/jackett
    ports:
      - "{{jackett.port}}:{{jackett.port}}"
    env:
      PUID: "{{uid.stdout}}"
      PGID: "{{gid.stdout}}"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/jackett:/config"
    restart_policy: always
    network_mode: host
    state: started
