---
- name: Stop and remove any existing container
  docker_container:
    name: jackett
    state: absent

- name: Create and start container
  docker_container:
    name: jackett
    image: linuxserver/jackett
    published_ports:
      - "127.0.0.1:9117:9117"
    env:
      PUID: "{{uid.stdout}}"
      PGID: "{{gid.stdout}}"
      VIRTUAL_HOST: "jackett.{{domain}}"
      VIRTUAL_PORT: 9117
      LETSENCRYPT_HOST: "jackett.{{domain}}"
      LETSENCRYPT_EMAIL: "{{email}}"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/jackett:/config"
    restart_policy: always
    state: started
    networks:
      - name: cloudbox
        ipv4_address: 172.18.0.11
        aliases:
          - jackett
