---
  - name: "Get {{user}} uid"
    shell: "id -u {{user}}"
    register: uid

  - name: "Get {{user}} gid"
    shell: "id -g {{user}}"
    register: gid
      
  - name: Install common packages
    apt: "name={{item}} state=installed"
    with_items:
      - unrar
      - unzip
      - p7zip
      - python-pip
      - python3-pip
      - python-passlib
      - curl
      - sqlite3
      - vnstat
      - tree
      - lsof
      - man-db
      - ksmtuned
      - git
      - pwgen
      - rsync
      - logrotate
      - htop
      - iotop
      - nload
      - fail2ban
      
  - name: Install common pip modules
    pip: "name={{item}} state=latest"
    with_items:
      - docker-py
      - speedtest-cli

  - name: Create common directories
    file: "path={{item}} state=directory mode=0775 owner={{user}} group={{user}} recurse=true"
    with_items:
      - /mnt/local
      - /mnt/local/.unionfs-fuse
      - /mnt/local/Media/TV
      - /mnt/local/Media/Movies
      - /opt
      - /opt/plexdrive
      - /opt/sonarr
      - /opt/radarr
      - /opt/nzbget
      - /opt/nzbget/scripts
      - /opt/rutorrent
      - /opt/jackett
      - /opt/nzbhydra
      - /opt/plex
      - /opt/plexpy
      - /opt/plex_autoscan
      - /opt/unionfs_cleaner
      - /opt/rclone
      - /opt/nginx-proxy
      - /opt/plexrequests
      - /opt/organizr
      - /opt/portainer
      - "/home/{{user}}/.config/rclone"
      - "{{nzbget.downloads}}"
      - "{{rutorrent.downloads}}"
      - "{{plex.transcodes}}"
      
  - name: Check plexdrive mount folder exist
    stat:
      path: /mnt/plexdrive
    register: plexdrive_mnt

  - name: Create /mnt/plexdrive
    file:
      path: /mnt/plexdrive
      state: directory
      mode: 0755
      owner: "{{user}}"
      group: "{{user}}"
      recurse: true
    when: plexdrive_mnt.stat.exists == False

  - name: Check unionfs mount folder exist
    stat:
      path: /mnt/unionfs
    register: unionfs_mnt

  - name: Create /mnt/unionfs and subdirs
    file: "path={{item}} state=directory mode=0775 owner={{user}} group={{user}} recurse=true"
    with_items:
      - /mnt/unionfs
      - /mnt/unionfs/Media
      - /mnt/unionfs/Media/Movies
      - /mnt/unionfs/Media/TV
    when: unionfs_mnt.stat.exists == False