---
  - name: Create common groups
    group: name={{item}} state=present
    with_items:
      - docker
      - "{{user}}"

  - name: "Create user {{user}}"
    user:
      name: "{{user}}"
      groups: "{{user}},docker"
      password: $6$zB04ETFuezaIT$CnhuAgxVir31qsE3.hLjv.WjMWNLFsrAtuK5mjHUx7gMnzGv7awJq8ZhEK8F/8UBNOjyoauaQ3Wle.GoYC2i1.
      update_password: on_create
      append: yes
      shell: /bin/bash

  - name: "Get {{user}} uid"
    shell: "id -u {{user}}"
    register: uid

  - name: "Get {{user}} gid"
    shell: "id -g {{user}}"
    register: gid
      
  - name: Install common packages
    apt: name={{item}} state=installed
    with_items:
      - unrar
      - unzip
      - p7zip
      - python-pip
      - python3-pip
      - curl
      - sqlite3
      - vnstat

  - name: Create common directories
    file: "path={{item}} state=directory mode=0775 owner={{user}} group={{user}}"
    with_items:
      - /mnt/plexdrive
      - /mnt/unionfs
      - /mnt/local
      - /mnt/local/Media/TV
      - /mnt/local/Media/Movies
      - /opt/plexdrive
      - /opt/sonarr
      - /opt/radarr
      - /opt/nzbget
      - /opt/rutorrent
      - /opt/jackett
      - "{{nzbget.downloads}}"
      - "{{rutorrent.downloads}}"
      