---
  - name: Create required groups
    group: name={{item}} state=present
    with_items:
      - docker
      - seed

  - name: "Create seed {{user}}"
    user:
      name: seed
      groups: seed,docker
      password: $6$zB04ETFuezaIT$CnhuAgxVir31qsE3.hLjv.WjMWNLFsrAtuK5mjHUx7gMnzGv7awJq8ZhEK8F/8UBNOjyoauaQ3Wle.GoYC2i1.
      update_password: on_create
      append: yes
      shell: /bin/bash
      
  - name: Install required packages
    apt: name={{item}} state=installed
    with_items:
      - unrar
      - unzip
      - p7zip
      - python-pip
      - python3-pip
      - curl
      - sqlite3

  - name: Create common directories
    file: "path={{item}} state=directory mode=0775 owner=seed group=seed"
    with_items:
      - /mnt/plexdrive
      - /mnt/unionfs
      - /mnt/local
