---
- name: Install required packages
  apt: "name={{item}} state=installed"
  with_items:
    - apt-transport-https
    - ca-certificates
    - software-properties-common

- name: Add official gpg signing key
  apt_key:
    id: 0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add official repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable" 

- name: Install docker
  apt:
    name: docker-ce
    state: installed
    update_cache: yes

- name: Install ctop
  get_url:
    url:  https://github.com/bcicen/ctop/releases/download/v0.6.0/ctop-0.6.0-linux-amd64
    dest: /usr/local/bin/ctop
    mode: 0755
    owner: root
    group: root
    force: yes

- name: Create cloudbox network
  docker_network:
    name: cloudbox
    ipam_options:
      subnet: '172.18.0.0/32'
      gateway: '172.18.0.1'
      iprange: '172.18.0.0/48'
