---
- name: Install required packages
  apt: name={{item}} state=installed
  with_items:
    - apt-transport-https
    - ca-certificates
    - software-properties-common

- name: Add official gpg signing key
  apt_key:
    id: 0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add official repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"

- name: Update apt
  apt: 
    update_cache: yes

- name: Install docker
  apt:
    name: docker
    state: installed
