---
- name: Stop and remove any existing container
  docker_container:
    name: traefik
    state: absent

- name: Import config.toml
  template:
    src: config.toml.js2
    dest: /opt/traefik/config.toml
    owner: "{{user}}"
    group: "{{user}}"
    mode: 0775
    force: yes

- name: Create htpasswd
  htpasswd:
    path: /opt/traefik/htpasswd
    name: "{{user}}"
    password: "{{web_passwd}}"
    owner: "{{user}}"
    group: "{{user}}"
    mode: 0775

- name: Ensure acme.json exists
  file:
    path: "/opt/traefik/acme.json"
    state: touch
    owner: "{{user}}"
    group: "{{user}}"
    mode: 0600
    force: yes

- name: Create and start container
  docker_container:
    name: traefik
    image: "traefik:latest"
    published_ports:
      - "127.0.0.1:8080:8080"
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/traefik/config.toml:/traefik.toml"
      - "/opt/traefik:/config"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - name: cloudbox
        aliases:
          - traefik
    labels:
      traefik.port: "8080"
    restart_policy: always
    state: started
