---
- name: Stop and remove any existing container
  docker_container:
    name: traefik
    state: absent

- name: Create and start container
  docker_container:
    name: traefik
    image: "traefik:latest"
    published_ports:
    # set below 8080 to 127.0.0.1 later
      - "8080:8080"
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/dev/null:/traefik.toml"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    command: --web --docker --docker.domain={{domain}} --logLevel=DEBUG
    networks:
      - name: cloudbox
        aliases:
          - traefik
    restart_policy: always
    labels:
      traefik.backend: "cloudbox"
    state: started
