---
  - name: "Get {{user}} uid"
    shell: "id -u {{user}}"
    register: uid
    when: uid is not defined

  - name: "Get {{user}} gid"
    shell: "id -g {{user}}"
    register: gid
    when: gid is not defined

  - name: Create required directories
    file: "path={{item}} state=directory mode=0775 owner={{user}} group={{user}} recurse=true"
    with_items:
      - /opt/tvheadend

  - name: Stop and remove any existing container
    docker_container:
      name: tvheadend
      state: absent

  - name: Create and start tvheadend container
    docker_container:
      name: tvheadend
      image: "linuxserver/tvheadend:release-4.2"
      published_ports:
        - "127.0.0.1:9981:9981"
        - "9982:9982"
      env:
        PUID: "{{uid.stdout}}"
        PGID: "{{gid.stdout}}"
        VIRTUAL_HOST: "tvheadend.{{domain}}"
        VIRTUAL_PORT: 9981
        LETSENCRYPT_HOST: "tvheadend.{{domain}}"
        LETSENCRYPT_EMAIL: "{{email}}"
      volumes:
        - "/etc/localtime:/etc/localtime:ro"
        - "/opt/tvheadend:/config"
      networks:
        - name: cloudbox
          ipv4_address: 172.18.0.20
          aliases:
            - tvheadend
      restart_policy: always
      state: started

  - name: Stop and remove any existing container
    docker_container:
      name: plexheadend
      state: absent

  - name: Create and start plexheadend container
    docker_container:
      name: plexheadend
      image: "wrboyce/plexheadend"
      exposed_ports:
        - 80
      published_ports:
        - "127.0.0.1:81:80"
      env:
        PLEXHEADEND_TVH_HOST: tvheadend
        PLEXHEADEND_PROXY_HOSTNAME: plexheadend
        PLEXHEADEND_TUNERS: 8
      user: "{{uid.stdout}}:{{gid.stdout}}"
      volumes:
        - "/etc/localtime:/etc/localtime:ro"
      networks:
        - name: cloudbox
          ipv4_address: 172.18.0.21
          aliases:
            - plexheadend
      restart_policy: always
      state: started
