---
- name: "Create and start container"
  vars:
    docker_cmd: "docker run -d --name=plex -p {{plex.port}}:{{plex.port}}/tcp -e PUID={{uid.stdout}} -e PGID={{gid.stdout}} -e CHANGE_CONFIG_DIR_OWNERSHIP=false -v /etc/localtime:/etc/localtime:ro -v /opt/plex:/config -v {{plex.transcodes}}:/transcode -v /mnt/unionfs/Media:/data --restart=always --network=host plexinc/pms-docker"
  command: "{{docker_cmd}}"