---
- name: "Create and start container"
  vars_prompt:
    - name: "claim_token"
      prompt: "enter your claim token from http://www.plex.tv/claim"
  vars:
    docker_cmd: "docker run -d --name=plex -p {{plex.port}}:{{plex.port}}/tcp -e PUID={{uid.stdout}} -e PGID={{gid.stdout}} -v /etc/localtime:/etc/localtime:ro -v /opt/plex:/config -v {{plex.transcodes}}:/transcode -v /mnt/unionfs/Media:/data --restart=always --network=host plexinc/pms-docker"
  command: "{{docker_cmd}}"