---
- name: Stop and remove any existing container
  docker_container:
    name: plex
    image: plexinc/pms-docker
    state: absent

- name: Create and start container
  docker_container:
    name: plex
    image: "plexinc/pms-docker:{{plex.tag}}"
    published_ports:
      - "{{plex.port}}:{{plex.port}}/tcp"
    env:
      PLEX_UID: "{{uid.stdout}}"
      PLEX_GID: "{{gid.stdout}}"
      CHANGE_CONFIG_DIR_OWNERSHIP: false
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/plex:/config"
      - "{{plex.transcodes}}:/transcode"
      - "/mnt/unionfs/Media:/data"
    restart_policy: always
    network_mode: host
    state: started

- name: Check WebTools exists
  stat:
    path: "/opt/plex/Library/Application Support/Plex Media Server/Plug-ins/WebTools.bundle"
  register: webtools_bundle

- name: Wait for Plug-ins folder to be created by Plex
  wait_for:
    path: "/opt/plex/Library/Application Support/Plex Media Server/Plug-ins"
    state: present
  when: webtools_bundle.stat.exists == False

- name: Install WebTools
  unarchive:
    src: https://github.com/ukdtom/WebTools.bundle/releases/download/2.4.1/WebTools.bundle.zip
    dest: "/opt/plex/Library/Application Support/Plex Media Server/Plug-ins"
    copy: no
    owner: "{{user}}"
    group: "{{user}}"
    mode: 0775
  when: webtools_bundle.stat.exists == False