---
- name: Stop and remove any existing container
  docker_container:
    name: plex
    image: plexinc/pms-docker
    state: absent

- name: Create and start container
  docker_container:
    name: plex
    image: "plexinc/pms-docker:{{plex.tag}}"
    ports:
      - "{{plex.port}}:{{plex.port}}/tcp"
    env:
      PLEX_UID: "{{uid.stdout}}"
      PLEX_GID: "{{gid.stdout}}"
      CHANGE_CONFIG_DIR_OWNERSHIP: false
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/plex:/config"
      - "{{plex.transcodes}}:/transcode"
      - "/mnt/unionfs/Media:/data"
    restart_policy: always
    net: host
    state: started
