---
- name: Stop and remove any existing container
  docker_container:
    name: znc
    state: absent

- name: Setup default sonarr docker volume to be merged
  set_fact:
    znc_volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "{{mnt.docker_data}}/znc:/config"

- name: Create and start container
  docker_container:
    name: znc
    image: "linuxserver/znc"
    published_ports:
      - "6501:6501/tcp"
    volumes: "{{znc_volumes + docker_volumes.znc|default(omit)}}"
    restart_policy: always
    networks:
      - name: cloudbox
        ipv4_address: 172.18.0.20
        aliases:
          - znc
    state: started
